/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'petercolapietro' at '10/17/14 8:08 PM' with Gradle 2.1
 *
 * @author petercolapietro, @date 10/17/14 8:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
